# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jl4rJxHHalptpB5XCjSf4IXuszT0G9Sp
"""

pip install rasterio

import rasterio

# Open the raster file
raster_file = rasterio.open('/content/data/LAKE_ALICE.tif')

# Read the raster data as a NumPy array
raster_data = raster_file.read()

# Print the shape and data type of the NumPy array
print(raster_data.shape)
print(raster_data.dtype)

import rasterio
import numpy as np

# Open the raster file
raster_file = rasterio.open('/content/data/LAKE_ALICE.tif')

# Read the raster data as a NumPy array
raster_data = raster_file.read()

# Define the constant value to add
add_value = 10

# Add the constant value to the raster data
raster_data += add_value

# Write the modified raster data back to a new file
with rasterio.open('/content/data/output', 'w', **raster_file.meta) as dst:
    dst.write(raster_data)

new_raster_file = rasterio.open('/content/data/output')

# Read the new raster data as a NumPy array
new_raster_data = new_raster_file.read()

# Print the shape and data type of the NumPy array
print(new_raster_data.shape)
print(new_raster_data.dtype)

# Print the minimum and maximum pixel values
print(new_raster_data.min())
print(new_raster_data.max())

